### ISSUE TITLE
The NAO code cannot compile on VS2017

### ISSUE THREAD

**Issue by puredragon8** [bhuman/BHumanCodeRelease#12]
After I released the code from generate.cmd,I opened the .sln file and  compiled the NAO code in the Develop configuration.But it cnnot build and show these errors.Could you please tell me why?Thank you![
![tim 20171130110001](https://user-images.githubusercontent.com/34115782/33410945-a52a21ce-d5bd-11e7-9a63-37a14e56f5ef.png)
](url)

**Comment by puredragon8** [comment]
The photo cannot show and the errors is actually like these:
3>..Src/Modules/BehaviorControl/BehaviorControl/BehaviorControl.cpp
3>..Src/Modules/BehaviorControl/CameraControlEngine/CameraControlEngine.cpp
3>env: 'ccache': No such file or directory
3>..Src/Modules/BehaviorControl/LEDHandler/LEDHandler.cpp
3>env: 'ccache': No such file or directory
3>..Src/Modules/BehaviorControl/Libraries/LibCodeReleaseProvider.cpp
3>env: 'ccache': No such file or directory
3>env: 'ccache': No such file or directory

**Comment by bhuman** [comment]
Hi,

the chapter "Getting Started" asks you to install "Cygwin x86 / x64 (available at http://www.cygwin.com) with the additional packages rsync, openssh, ccache, and clang." Did you do that?

**Comment by puredragon8** [comment]
Yes!It is this question.I have fixed it.Thank for your help sincerely
