### ISSUE TITLE
Nao can't stand up after falling.

### ISSUE THREAD

**Issue by carlprilo** [bhuman/BHumanCodeRelease#13]
Our Nao can't stand up with this codes, but in SimRobot the virtual Nao could stand up. I wonder wether this codes have the part of getting up, or we ignored some  necessary steps?

**Comment by bhuman** [comment]
Do you have the newest version installed (March 8)?

**Comment by carlprilo** [comment]
The newest version works! Thank you!

**Comment by carlprilo** [comment]
The newest version works! Thank you!
