### ISSUE TITLE
cannot execute 'installrobot' shell

### ISSUE THREAD

**Issue by jizhuozhi** [bhuman/BHumanCodeRelease#15]
On macOs 10.13.2,
```
Unknown cipher type'arcfour'
[FATAL]: Can't change access rights on NAO's'.ssh'folder error.
```
appeared when `installRobot` was executed.
This seems to be because the weak encryption algorithm RC4 is used, but SSh client has removed it. I remove `-c arcfour` from `sshOptions` and can execute `installrobot`, but I don't know if there will be an unknown effect.

**Comment by bhuman** [comment]
The effect is, that deploying is a lot slower (four to five times). NAO's Atom is rather slow processing more complex cyphers. However, as you recognized, newer versions of `ssh` do not support the weak cypher anymore. We now use `aes128-ctr` if `arcfour` is not available.

**Comment by jizhuozhi** [comment]
Thanks for your help sincerely!
