### ISSUE TITLE
Use the 'WalkAtRelativeSpeed' option, but the robot behaving as' waving '.

### ISSUE THREAD

**Issue by jizhuozhi** [bhuman/BHumanCodeRelease#16]
Use the 'WalkAtRelativeSpeed' option, but the robot behaving as' waving '.
I also try to use 'WalkAtAbsoluteSpeed',but has no effect.
```
option(PlayingState)
{
  initial_state(demo)
  {
    action
    {
      //Demo();
    //WalkAtRelativeSpeed(Pose2f(0.f,0.8f,0.f));
    WalkAtAbsoluteSpeed(0,10.f,0.f);
    }
  }
}
```

**Comment by jizhuozhi** [comment]
Used CodeRelease2017 newest commit

**Comment by jizhuozhi** [comment]
ten minute age, I used sound 'arm.wav' as a flag , it worked normal.
```
option(PlayingState)
{
  initial_state(demo)
  {
    action
    {
      //Demo();
    //WalkAtRelativeSpeed(Pose2f(0.f,0.8f,0.f));
    //WalkAtAbsoluteSpeed(0,10.f,0.f);
    PlaySound("arm.wav");
    }
  }
}

```
I could hear sound 'arm', but robot also behaving as 'waving'

**Comment by bhuman** [comment]
Use the Behavior View to see what's really going on.

**Comment by jizhuozhi** [comment]
Thanks for your help sincerely, and I will have a try!
