### ISSUE TITLE
can't make in Make/Linux in ubuntu18.04

### ISSUE THREAD

**Issue by Robin-Wujw** [bhuman/BHumanCodeRelease#18]
When I  type make in Make/Linux  with ubuntu18.04lts 
It shows that  fatal error:       'QTreeWidget' file not found,'QCloseEvent'#include <QAction>  and  'QMainWindow''QDockWidget'  file not  found.but qt5 is installed in my ubuntu .
thanks a lot if you can reply to  me .

**Comment by bhuman** [comment]
Use
```
QTINCLUDE = `find /usr/include /usr/local/include -name qt5 -type d`
```
in the Makefile

**Comment by Robin-Wujw** [comment]
thanks!  I solve it  !!
but an error has appeared that ./Util/Buildchain/clang/include/emmintrin.h:692:19: error: use of undeclared identifier '__builtin_ia32_pavgb128'
how can i solve it ?

**Comment by bhuman** [comment]
We haven't solved that yet.

**Comment by Robin-Wujw** [comment]
ok,and thanks all the same！

**Comment by gortium** [comment]
Install clang-4.0:
`sudo apt-get install clang-4.0`
And change the line 65 of the file Make/Common/Marefile to:
`"env CCACHE_CPP2=yes $(utilDirRoot)/Buildchain/Linux/bin/ccache clang++-4.0 -D__extern_always_inline=inline"`

**Comment by bhuman** [comment]
There is no target "install". The software is directly used from the directory "Build/...". In most cases, it is started from an IDE.
