### ISSUE TITLE
Flashing NAO and compiling codes from ubuntu 18.04

### ISSUE THREAD

**Issue by Burnedduk3** [bhuman/BHumanCodeRelease#20]
Hi !
I'm from Universidad de la Sabana Colombia, we are aspiring to enter the robocup tournament for the next year, we are having troubles when we try to copyfiles to the NAO and we get an error that says stopping Bhuman and we dont know what is happening, also I think that we broke the operative system of one NAO could you help us with that ? also do you know where we can get the NAO os ? please help us :)

**Comment by Burnedduk3** [comment]
I forgot to mention that the last thing we did was the install robot command

**Comment by bhuman** [comment]
What kind of NAO do you have?

**Comment by bhuman** [comment]
With NAOqi 2.1.4?

**Comment by Burnedduk3** [comment]
yes

**Comment by bhuman** [comment]
The cypher "arcfour" used by several scripts is not working anymore with newer versions of ssh.

**Comment by Burnedduk3** [comment]
yes we saw that in other issue but when we tried to make the ./installrobot we messed up, also how we can uploud the Bhuman code to our now for starters

**Comment by Burnedduk3** [comment]
when we run the installRobot command we don't get what to do next

**Comment by bhuman** [comment]
installRobot should end with rebooting the robot. Anyway, you can always use SoftBank's Flasher tool to restore the NAO to its factory settings.

**Comment by Burnedduk3** [comment]
thanks for the help there, an other question where do I change the cipher to dowload the logs ?

**Comment by Burnedduk3** [comment]
and also how do we manage wireless configuration, we tried changing: Config/Robots/*robotName*/network.cfg
/Install/Network/wired and wireless 
to our own ip's 
/install/Network/Profiles and we did our own like this:

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
  ssid="Red Wi-Fi de LUX1"
  scan_ssid=1
  proto=WPA2
  key_mgmt=WPA-PSK
  pairwise=TKIP
  group=TKIP
  psk="informaticaSabana"
}
our network is a wpa-wpa2 security.
thanks in advanced

**Comment by bhuman** [comment]
Search the scripts under Make and Install for "-c arcfour" and remove it. That should work, but it will be a lot slower than before.

**Comment by bhuman** [comment]
Read our team report. The wireless setup is described in it.

**Comment by Burnedduk3** [comment]
we read the wirless configuration but we dont get what to do because we already did it
