### ISSUE TITLE
SimRobot executable not running simulations

### ISSUE THREAD

**Issue by Master1624** [bhuman/BHumanCodeRelease#21]
My issue is when I'm running the executable of SimRobot, I select any scene that's in the directory on Scenes and then it shows up this issue:
`Illegal instruction (core dumped)`
How can I fix the issue?

**Comment by bhuman** [comment]
Your processor is probably not compatible with the compiler settings. Try to edit the settings in `Make/Common/Marefile`. However, it might be possible that the code will not compile anymore.
