### ISSUE TITLE
Compiling issue 

### ISSUE THREAD

**Issue by teodoroKernel** [bhuman/BHumanCodeRelease#22]
Hi.
We´re using windows 10-visual studio 2017 and during the compiling process we tried to compile simRobot core 2 but several errors appeared in the prosecution.
Those errors are listed below :

Error  code	C1047	t'..\..\Util\SimRobot\Util\ode\Windows\lib\ode_double.lib' A creator was compiled before other previous objects; compile libraries and other previous objects	SimRobotCore2	C:\Users\kernel\Desktop\B-HUMAN\BHumanCodeRelease-master\BHumanCodeRelease-master\Make\VS2017\LINK	1	

2.Error code LNK1257	Description                       Proyect	                 File	
                                   error of code generation    SimRobotCore2	C:\Users\kernel\Desktop\B-HUMAN\BHumanCodeRelease-master\BHumanCodeRelease-master\Make\VS2017\LINK	1

3.Error code MSB6006 Code	Description	Proyect		     File
Error                                         "cmd.exe"	SimRobot	      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171	
	
thanks a lot if you can reply to us .

**Comment by bhuman** [comment]
The ODE libraries need to be recompiled with the latest version of Visual Studio. There is a `.sln` file somewhere under `Util/SimRobot/Util/ode/Windows/src`. The libraries that need to be replaced are located in `Util/SimRobot/Util/ode/Windows/lib`
