### ISSUE TITLE
Unknown cipher type 'arcfour'

### ISSUE THREAD

**Issue by Master1624** [bhuman/BHumanCodeRelease#24]
How can I fix the arc four issue when I'm deploying the NAO in the bush? The problem appears in macOS.

**Comment by bhuman** [comment]
Search for "-c arcfour" in the Finder and remove it from the ssh commands. If you like, you can use "-c aes128-ctr" instead, which is a little faster than the default.

**Comment by Master1624** [comment]
I've already done that, but in the moment to make the deploy in the bush, it appears that issue. What else can I do?

**Comment by bhuman** [comment]
According to `grep`, the cipher is set in the following files (ignoring symbolic links). Maybe you missed one: 
```
Install/Include/bhumanBase
Make/Common/copyfiles
Make/Common/downloadLogs
```
