### ISSUE TITLE
unknown type name on ubuntu 16.04

### ISSUE THREAD

**Issue by yuanzhouxue** [bhuman/BHumanCodeRelease#26]
when i make in Make/Linux, I got the following errors:
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:22:1: error: unknown type name 'QT_WARNING_DISABLE_DEPRECATED'

It didn't appear before I use BHumanCodeRelease2015 to find a red ball. I want to know why this happen and how to solve it.
Thanks.

**Comment by bhuman** [comment]
Good luck.

**Comment by rperezdattari** [comment]
For anyone still having this issue try to check if your qt version is qt5. Another source for error is having the anaconda qt
