### ISSUE TITLE
It'll flash back when we try to add phase by using kick view

### ISSUE THREAD

**Issue by Tank1997** [bhuman/BHumanCodeRelease#27]
It's strange that my teammate's computer can normal work,but several times later,It will also flash back.
my system is Linux 18.04,and my teammate's is 16.04

**Comment by dsfd123** [comment]
thanks a lot if you can reply to me

**Comment by bhuman** [comment]
What does "flash back" mean? As far as I can see, the KickView works fine on Ubuntu 18.04. It may be a driver issue.

**Comment by dsfd123** [comment]
"flash back" means crash,and when we press "add phase",the terminal tells us that it's a segmentation fault.And if it's a driver issue,is there any method to solve this problem?

**Comment by bhuman** [comment]
It actually crashes when adding a phase. I found no other crash. The crash happens inside Qt during a call to `QTabWidget::insertTab`. However, it does not happen on other platforms (Windows, macOS).

With the debug version of Qt installed, you could try to find the reason using a debugger.
