### ISSUE TITLE
issue in connnection with simulator

### ISSUE THREAD

**Issue by priyashkla** [bhuman/BHumanCodeRelease#28]
I am using this code and installed all required packaged excluding alcommon but in 2.4 all settings given for real robot nao.In 2.7 giving for simulation but  no settings given for team creation .it is displaying team members in gui but no connection established.Is there any defined steps how we can use it in simulator?

**Comment by priyashkla** [comment]
i just downloaded the code from here https://github.com/bhuman/BHumanCodeRelease
then follow the steps from 2.1 to 2.3  in(https://www.b-human.de/downloads/publications/2017/coderelease2017.pdf).2.4,2.5,2.6 given all the settings for real robot but i want to do first in simulator so i followed 2.7 but no settings given here for team creation. When i am opening the bush file(build/linux/bush/develop/bush) simulator is opening but with blank team .I created team as
cd  Install
./ createRobot  -t 1 -r 4 Penny
./ createRobot  -t 1 -r 4 Priya as lan proxy is(172.31.1.4)
Now i want to know how i can add team members in team ?
Is there any game rules or instruction set that we can use for more understanding about it?
I am using 16.04 ubuntu

**Comment by bhuman** [comment]
There is a list of robots on the right side of the bush. It may be hidden by default.

**Comment by priyashkla** [comment]
![screenshot from 2018-09-10 10-28-21](https://user-images.githubusercontent.com/33479052/45264713-a9977100-b45e-11e8-9ced-00de1fe905bb.png)
![screenshot from 2018-09-10 10-28-40](https://user-images.githubusercontent.com/33479052/45264714-a9977100-b45e-11e8-97d6-0efde743f2eb.png)

**Comment by bhuman** [comment]
You have to drag robots to the slots 1-6 (the upper ones, the lower ones are for substitutes) and select their checkboxes. Then they are selected and commands will apply for them.

**Comment by priyashkla** [comment]
k thank one more thing
./ createRobot -t 1 -r 4 Penny
Is above command for creating team member? or team?
what can be minimum or maximum team size

**Comment by bhuman** [comment]
It just creates an individual robot. The "team" part is that the SPL rules say that each team has a number and it uses this number as its subnet in the ip address of their robots. In your example, the team number would be "1", which actually is the number of UT Austin Villa. Teams can have an arbitrary number of robots. However, in a match, each robot gets a player number that is independent from its IP address. The player numbers range from 1 to 6.

**Comment by priyashkla** [comment]
i added a robot by 172.31.1.4,172.31.1.5,172.31.1.6,172.31.1.7
but when i starts  simulator it's showing IP 192.168.5.10 for connection and finally not able to connect robot.
My lan proxy is 172.31.1.4

**Comment by bhuman** [comment]
The file Config/Scenes/Includes/connectDialog.con is not automatically updated when creating new robots. You have to change the IP addresses manually in that file.

**Comment by priyashkla** [comment]
ok thanks
but it is not connected showing No connection to 172.31.1.4 established!
still this is my lan proxy
i selected 2 robots as a team member(172.31.1.4 ,172.31.1.5) but only one is displaying

**Comment by bhuman** [comment]
Have you deployed the B-Human software to the robot? You wrote above that you did not install alcommon, which means that you could not have compiled the software for the robot.

**Comment by priyashkla** [comment]
but it is written as 
Please note that this package is only required to compile the code for the actual NAO robot.

**Comment by priyashkla** [comment]
http://naoqi-sdk-2.1.4.13-linux32.tar.gz/ is given to download and install with installAllcommon script
but my system is 64 bit ubuntu 16.04

**Comment by bhuman** [comment]
You try to connect to the actual NAO robot. This will only work if our software is running on the robot. The download file is the correct one, because NAO runs a 32 bit Linux.

**Comment by priyashkla** [comment]
firstly i want to work on simulator then i will do on real robot please suggest me for simulator only.
when i am running command
Priya@priya-HCL-Desktop:~/Downloads/BHumanCodeRelease-master/Install$ ./installAlcommon naoqi-sdk-2.1.4.13-linux32.tar.gz
Unpacking required content...tar (child): naoqi-sdk-2.1.4.13-linux32.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by priyashkla** [comment]
previous command worked as
priya@priya-HCL-Desktop:~/Downloads/BHumanCodeRelease-master/Install$ ./installAlcommon 'naoqi-sdk-2.1.4.13-linux32.tar.gz'
Unpacking required content...Done
Copying alcommon headers to destination...Done
Copying alcommon library to destination...Done
Copying boost headers to destination...Done
Cleaning up...Done
but in deploy giving error like this
![image](https://user-images.githubusercontent.com/33479052/45267694-2a6e6100-b48f-11e8-8f41-c80b9f42925b.png)

**Comment by bhuman** [comment]
If you just want to use the simulator, you do not any of this. Just start the simulator and open one of the scenes in Config/Scenes, e.g. BH*.ros2.
installAlcommon will not download the archive. You only can do that manually with your account at Softbank‘s website.

**Comment by priyashkla** [comment]
priya@priya-HCL-Desktop:~/Downloads/BHumanCodeRelease-master/Install$ ./installAlcommon 'naoqi-sdk-2.1.4.13-linux32.tar.gz'
Unpacking required content...Done
Copying alcommon headers to destination...Done
Copying alcommon library to destination...Done
Copying boost headers to destination...Done
Cleaning up...Done
but in deploy giving error like this
image

**Comment by bhuman** [comment]
You have installed the robot using the script `installRobot`?

**Comment by bhuman** [comment]
You should open the .ros2 files with the Simulator.

**Comment by priyashkla** [comment]
priya@priya-HCL-Desktop:~/Downloads/BHumanCodeRelease-master/Install$ ./installRobot 172.31.1.4
[INFO]: Copying authorized keys. If prompted please enter password twice (usually nao).
[FATAL]: Can't change access rights on NAO's '.ssh' folder

**Comment by bhuman** [comment]
Your nao is freshly installed with the image file specified in the description?

**Comment by priyashkla** [comment]
not getting u installRobot  is required for real robot but i want to check all d game application in simulator
.We have 3 nao robots but initially i want to check all functionality in simulator only.
IT would be helpful ,if u told me how i can use simulator with all functionality.

**Comment by bhuman** [comment]
Read the report.
