### ISSUE TITLE
Issue after executing the installRobot script on MacOS

### ISSUE THREAD

**Issue by oraki23** [bhuman/BHumanCodeRelease#29]
Hi, 

I'm currently trying to copy the code to my NAO. (note: I'm using MacOS and XCode) for the first time.
To do so, I start with a factory reset of my robot, then I do the script 
./createRobot -t 45 -r 8 Glados 
to create my robot, I then copy the robot Ids by doing the script:
./addRobotIds -ip 169.254.201.219 Glados

Everything works up until this point

And then I execute:
./installRobot 169.254.201.219
which reboots the NAO.

After rebooting, I'm not able to see the NAO anywhere on my network, I can't connect to it via bush, copyfile, login, ssh or other. Even the router i'm using don't see it on his network, when I access to the administrative panel. 
I tried changing the arcfour cipher to nothing (removing the lines) and to the cipher aes128-ctr (as specified in another issue), and still no changes in the result.
I even tried to execute manually (via ssh) all the lines to copy the files and install that are in the installRobot file.

- Is there any reason why I can't connect to my NAO after my ./installRobot ? Is this a network issue? Do I have to connect via a different IP than the one I use when executing the installRobot (169.254.201.219)?
- Is there any different setup to do because I'm on Mac (because other people can configure it on Linux and it works)?

**Comment by bhuman** [comment]
Read section 2.4.3.
