### ISSUE TITLE
What should I do ?

### ISSUE THREAD

**Issue by zjl898** [bhuman/BHumanCodeRelease#31]
```
root@z-Virtual-Machine:~/h/BHumanCodeRelease-master/Make/Linux# make
..Util/SimRobot/Src/SimRobot/StatusBar.cpp
../../Util/SimRobot/Src/SimRobot/StatusBar.cpp:2:10: fatal error: 'QAction' file
      not found
#include <QAction>
         ^~~~~~~~~
1 error generated.
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1
```
```
root@zjl-Virtual-Machine:~/h/BHumanCodeRelease-master/Make/Linux# qtchooser -l
4
5
default
qt4-x86_64-linux-gnu
qt4
qt5-x86_64-linux-gnu
qt5
```

My computer system is Ubuntu 18.04.1 LTS
My Qt5 is installed in"/usr/lib/x86_64-linux-gnu"
Please help me,thanks a lot!

**Comment by bhuman** [comment]
Hi,

we have replace the line in `Make/Linux/Makefile` by:
```
QTINCLUDE = `find /usr/include /usr/local/include -name qt5 -type d`
```

**Comment by priyashkla** [comment]
i got the same type of error
priya@priya:~/Downloads/BHumanCodeRelease-master/Make/Linux$ make
..Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp
..Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp
..Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp
..Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp
..Src/Modules/MotionControl/KickEngine/KickEngine.cpp
..Src/Modules/MotionControl/KickEngine/KickEngineParameters.cpp
..Src/Modules/MotionControl/KickEngine/KickEngineData.cpp
..Src/Modules/MotionControl/SpecialActions/SpecialActions.cpp
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:22:1: error: unknown type name 'QT_WARNING_DISABLE_DEPRECATED'
QT_WARNING_DISABLE_DEPRECATED
^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:23:1: error: expected unqualified-id
struct qt_meta_stringdata_StatusBar_t {
^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:32:14: error: unknown type name 'qt_meta_stringdata_StatusBar_t'
static const qt_meta_stringdata_StatusBar_t qt_meta_stringdata_StatusBar = {
             ^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:34:1: error: unknown type name 'qt_meta_stringdata_StatusBar_t'
QT_MOC_LITERAL(0, 0, 9), // "StatusBar"
^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_StatusBar_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:35:1: error: unknown type name 'qt_meta_stringdata_StatusBar_t'
QT_MOC_LITERAL(1, 10, 14), // "messageChanged"
^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_StatusBar_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:36:1: error: unknown type name 'qt_meta_stringdata_StatusBar_t'
QT_MOC_LITERAL(2, 25, 0), // ""
^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_StatusBar_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:37:1: error: unknown type name 'qt_meta_stringdata_StatusBar_t'
QT_MOC_LITERAL(3, 26, 7) // "message"
^
../../Build/Linux/SimRobot/Develop/moc_StatusBarDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_StatusBar_t, stringdata0) + ofs \
                      ^
7 errors generated.
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:22:1: error: unknown type name 'QT_WARNING_DISABLE_DEPRECATED'
QT_WARNING_DISABLE_DEPRECATED
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:23:1: error: expected unqualified-id
struct qt_meta_stringdata_RegisteredDockWidget_t {
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:32:14: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
static const qt_meta_stringdata_RegisteredDockWidget_t qt_meta_stringdata_RegisteredDockWidget = {
             ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:34:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(0, 0, 20), // "RegisteredDockWidget"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:35:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(1, 21, 12), // "closedObject"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:36:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(2, 34, 0), // ""
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:37:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(3, 35, 6), // "object"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:38:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(4, 42, 17), // "closedContextMenu"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:39:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(5, 60, 17), // "visibilityChanged"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:40:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(6, 78, 7), // "visible"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:41:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(7, 86, 4), // "copy"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:42:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(8, 91, 11), // "exportAsSvg"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:43:1: error: unknown type name 'qt_meta_stringdata_RegisteredDockWidget_t'
QT_MOC_LITERAL(9, 103, 11) // "exportAsPng"
^
../../Build/Linux/SimRobot/Develop/moc_RegisteredDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_RegisteredDockWidget_t, stringdata0) + ofs \
                      ^
13 errors generated.
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:22:1: error: unknown type name 'QT_WARNING_DISABLE_DEPRECATED'
QT_WARNING_DISABLE_DEPRECATED
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:23:1: error: expected unqualified-id
struct qt_meta_stringdata_MainWindow_t {
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:32:14: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
static const qt_meta_stringdata_MainWindow_t qt_meta_stringdata_MainWindow = {
             ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:34:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(0, 0, 10), // "MainWindow"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:35:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(1, 11, 8), // "openFile"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:36:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(2, 20, 0), // ""
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:37:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(3, 21, 8), // "fileName"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:38:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(4, 30, 12), // "unlockLayout"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:39:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(5, 43, 14), // "updateFileMenu"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:40:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(6, 58, 20), // "updateRecentFileMenu"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:41:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(7, 79, 14), // "updateViewMenu"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:42:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(8, 94, 15), // "updateAddonMenu"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:43:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(9, 110, 20), // "updateMenuAndToolBar"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:44:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(10, 131, 16), // "setGuiUpdateRate"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:45:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(11, 148, 4), // "rate"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:46:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(12, 153, 4), // "open"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:47:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(13, 158, 9), // "closeFile"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:48:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(14, 168, 5), // "about"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:49:1: error: unknown type name 'qt_meta_stringdata_MainWindow_t'
QT_MOC_LITERAL(15, 174, 9), // "loadAddon"
^
../../Build/Linux/SimRobot/Develop/moc_MainWindowDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MainWindow_t, stringdata0) + ofs \
                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:22:1: error: unknown type name 'QT_WARNING_DISABLE_DEPRECATED'
QT_WARNING_DISABLE_DEPRECATED
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:23:1: error: expected unqualified-id
struct qt_meta_stringdata_SceneGraphDockWidget_t {
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:32:14: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
static const qt_meta_stringdata_SceneGraphDockWidget_t qt_meta_stringdata_SceneGraphDockWidget = {
             ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:34:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(0, 0, 20), // "SceneGraphDockWidget"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:35:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(1, 21, 15), // "activatedObject"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:36:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(2, 37, 0), // ""
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:37:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(3, 38, 8), // "fullName"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:38:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(4, 47, 23), // "const SimRobot::Module*"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:39:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(5, 71, 6), // "module"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:40:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(6, 78, 17), // "SimRobot::Object*"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:41:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(7, 96, 6), // "object"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:42:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(8, 103, 5), // "flags"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:43:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(9, 109, 17), // "deactivatedObject"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:44:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(10, 127, 13), // "itemActivated"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:45:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(11, 141, 5), // "index"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:46:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(12, 147, 13), // "itemCollapsed"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:47:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(13, 161, 12), // "itemExpanded"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:48:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(14, 174, 17), // "openOrCloseObject"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:49:1: error: unknown type name 'qt_meta_stringdata_SceneGraphDockWidget_t'
QT_MOC_LITERAL(15, 192, 22) // "expandOrCollabseObject"
^
../../Build/Linux/SimRobot/Develop/moc_SceneGraphDockWidgetDevelopLinux.cpp:29:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_SceneGraphDockWidget_t, stringdata0) + ofs \
                      ^
19 errors generated.
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by priyashkla** [comment]
i am using 16.04 LTS but getting error
please provide better solution

**Comment by bhuman** [comment]
As the license says: "THIS SOFTWARE IS PROVIDED BY B-HUMAN ``AS IS''".

The 2018 code release will be out soon. However, for Linux it will only have been tested on Ubuntu 18.04.

**Comment by priyashkla** [comment]
i am using 16.04 LTS but getting error
please provide better solution


> As the license says: "THIS SOFTWARE IS PROVIDED BY B-HUMAN ``AS IS''".
> 
> The 2018 code release will be out soon. However, for Linux it will only have been tested on Ubuntu 18.04.

i m using 16.04 LTS
this code should work on this
pls suggest @bhuman

**Comment by priyashkla** [comment]
plaese i m waiting  for ur suggestion

**Comment by zjl898** [comment]
@bhuman Thanks a lot! Bhuman software is running succeed.But I found a new problem.My Ubuntu system is installed in virtual machine.How to set /BHumanCodeRelease-master/Install/Network/Profiles/default ?It needs WIFI,but the net of my virtual machine is bridging.
