### ISSUE TITLE
Visual Studio Error with ODE

### ISSUE THREAD

**Issue by japr123** [bhuman/BHumanCodeRelease#32]
Good afternoon B-Human team; I´ve been working with the help of your 2017 release code for the past 6 months and I've learned countless new tools and information just by reading and modifying your base. 

As soon as I saw your 2018 release code I tried to compile the project using Vs2017. Nonetheless, after following the instructions there is an error "LNK2001" regarding the usage of ODE libraries. I tried following a previous instruction of yours in which you suggested to compile the ODE lib and replace it on the src. 

I tried downloading the ode (.013) and the premake5 to compile the project but it failed and showed even more errors than at the beginning. 

I deleted everything once again and I am at a clean start. 
Could you help me install the project on Windows? (Win 10 x64) (Vs 2017)

**Comment by bhuman** [comment]
Do you use version 15.8, as the document says?

**Comment by bhuman** [comment]
Obviously not.
