### ISSUE TITLE
 Does the coderelease2018 provide an automatic conversion mechanism for the role? 

### ISSUE THREAD

**Issue by Heodel** [bhuman/BHumanCodeRelease#38]
We encountered a problem in the role conversion, does the code release provide an automatic conversion mechanism for the role? After I write my own characters, such as forwards, defenders, goalkeepers, how do I switch roles during the game?

**Comment by bhuman** [comment]
No, as we do not release our behavior code, the role computation code is not publicly available. You will have to develop and implement this functionality yourself.

**Comment by Heodel** [comment]
ok,thanks

**Comment by Saman-Khan** [comment]
Hi @Heodel can u please throw some light on how to assign cards to opponents?
Any help would be appreciated
