### ISSUE TITLE
Add opencv library to bhuman

### ISSUE THREAD

**Issue by yanghanbiao** [bhuman/BHumanCodeRelease#44]
hello,I wanted to add opencv to bhuman.And I install opencv3.10 to /Util/opencv/.Then I edited /Make/common/Nao.mare and SimulateNao.mare.I included opencv to the code.But when I make in /make/Linux/,I got some error.
ld: skipping incompatible ../../Util/opencv/lib/libopencv_video.so when searching for -lopencv_video
ld: cannot find -lopencv_video
ld: skipping incompatible ../../Util/opencv/lib/libopencv_objdetect.so when searching for -lopencv_objdetect
ld: cannot find -lopencv_objdetect
ld: skipping incompatible ../../Util/opencv/lib/libopencv_highgui.so when searching for -lopencv_highgui
ld: cannot find -lopencv_highgui
ld: skipping incompatible ../../Util/opencv/lib/libopencv_imgproc.so when searching for -lopencv_imgproc
ld: cannot find -lopencv_imgproc
ld: skipping incompatible ../../Util/opencv/lib/libopencv_core.so when searching for -lopencv_core
ld: cannot find -lopencv_core
ld: skipping incompatible ../../Util/opencv/lib/libippicv.a when searching for -lippicv
ld: cannot find -lippicv
ld: skipping incompatible ../../Util/opencv/lib/libz.a when searching for -lz
ld: cannot find -lz
Could you help me?

**Comment by yanghanbiao** [comment]
My system is ubuntu 18.4LTS

**Comment by bhuman** [comment]
Are you sure that you link the 32 bit version of the OpenCV libraries?

**Comment by yanghanbiao** [comment]
Thank you for your reminder.It seems that the simulateNao.mare needs 64 bit opencv static library and Nao.mare needs 32  bit static library.I have added opencv3.1 to bhuman successfully.But I have a doubt that why the copyfiles lost executable permission in Make/Linux/ path after I compiled opencv to bhuman?
And another doubt is that if I use the functions of opencv library ,wether the buman severe loss of efficiency?

**Comment by bhuman** [comment]
I don't know about the executable permissions, but OpenCV isn't really fast. That's why nobody uses it on a weak processor such as the one in the NAO.

**Comment by yanghanbiao** [comment]
So if I want to use a the visual processing algorithm of opencv,I needs to rewritting the code to bhuman for efficiency.

**Comment by bhuman** [comment]
The general approach is to design algorithms differently. Re-implementing the same algorithm may not necessarily make it faster.

**Comment by yanghanbiao** [comment]
It means that I have to understand deeply the principle of algorithm and combine the cases of RoboCup SPL to design a new algorithm.

**Comment by yanghanbiao** [comment]
It seems that bhuman uses classic algorithms in many places.
