### ISSUE TITLE
About Documentation 

### ISSUE THREAD

**Issue by Saman-Khan** [bhuman/BHumanCodeRelease#47]
Hi, I am trying to work on the code release. I have a few questions 
1 . There is a statement in document which I am unable to understand."SimRobot represents everything in the
simulation except for SimulatedNao." Can someone please explain what it means. 

2. Do u have some active community that can help beginners about basic questions related to code or the only method to get help is to post queries on this forum.
Looking forward for a positive response. Regards

**Comment by Saman-Khan** [comment]
Is there some detailed documentation available to use SIMROBOT for BHuman Code release? Or some tutorials on how to check different code modules in simulation environment. The code release documentation is confusing. Also, is there any active community where we can get help quickly.
Another thing, do I need to calibrate joints and camera before running simulation or is it only for hardware robot. A quick reply is appreciated

**Comment by chenqiao637** [comment]
邮件已收到，谢谢

**Comment by ahasselbring** [comment]
I basically already answered these questions in reply to your mail. Short summary:
1. That sentence explains the meaning of the "SimRobot" rows in the table above.
2. There is no community specific to the B-Human code release. If you have *specific* questions, you can open an issue here. But if you are confused about the code release in general, probably nobody has the time to help you. If you are actually interested in creating a team for the Standard Platform League, you may want to have a look at this document: https://spl.robocup.org/joining-robocup-spl/
3. Calibration is only necessary for real robots.
