### ISSUE TITLE
bhuman for nao v3.3

### ISSUE THREAD

**Issue by mmazinani2** [bhuman/BHumanCodeRelease#5]
Thank you so much for distributing your valuable codes through github.

We have 2 NAO ver 5 and 3 NAO Robocup Edition ver 3.3 robots.
We have successfuly installed the B-Human code on ver 5 robots but faced problems setting up the B-Human code on ver 3.3 robots.
We have tried to use your B-Human 2011 codes as 2012 codes seems to be designed for ver 3.3 robots with the head upgraded to ver 4.0. But our robot heads are ver 3.3 .

We have successfully finished the make process of 2011 code but failed to set it up on the robot.
Would you please kindly guide us how we could setup the robot or is there a page we could find the guide from the web?
Is there a link on the web that we could find required files and dependencies for 2011 code release?

Thank you so much for your kind helps.

**Comment by roefer** [comment]
There is http://www.b-human.de/downloads/bhuman11_coderelease.pdf . Since we have not installed or used a V3 since four years, we cannot help you with it. Sorry.

**Comment by mmazinani2** [comment]
Dear friend
thanks for your answer
I have read this link
The main problem is the requirements for installing this version of bhuman
Such as
nao-system-image-robocup-1.10.52.ext3.bz2
I could not find it
and also
The problem is when copying files on the robot. This work is not complete.
I am able to complete the installation on the robot version 2012
But bhuman can not run after installation.
I think this problem due to hardware differences between version 3.3 and 4.
Do you have a solution to offer me?
Again, thank you

**Comment by roefer** [comment]
There is no solution. The V3x is completely different from the V4. Different processor, different Linux, different camera, etc. Aldebaran offers no support anymore for the V3x. That's why you cannot find an OS image anymore.

**Comment by arezaie14** [comment]
Hello . I have one question about bhuman 2016 code release with nao version 5. Can we install this version of bhuman on nao version 5 ? I asked this question because we have crashed robot with bhuman version 2014. best regards

**Comment by bhuman** [comment]
Yes, you can install the code release 2016 on V5 NAOs. In fact, it is very risky to install older version on the current release of NAOqi, because Softbank changed something that sometimes lets older versions of our install script make the robots unusable.

**Comment by arezaie14** [comment]
thank you so much. i want to install release version December 8, 2016

**Comment by bhuman** [comment]
That's ok.

**Comment by arezaie14** [comment]
thank you

**Comment by Daniel-LYS** [comment]
friend,have u found nao-system-image-robocup-1.10.52.ext3.bz2?
