### ISSUE TITLE
Global Commands

### ISSUE THREAD

**Issue by Saman-Khan** [bhuman/BHumanCodeRelease#50]
![image](https://user-images.githubusercontent.com/15613013/185810719-b427b144-5c87-4e22-8cfc-dca680faed69.png)
The mvo command is giving syntax error. I loaded the scene BH.ros and it has a robot named robot3. When i give the command , mvo robot3 10 0 0[1 1 1] or something according to this syntax, i always get a syntax error. I am unable to move my robot using this command. Can u guide , what am I doing wrong?

**Comment by ahasselbring** [comment]
The object name given to this command must be fully qualified, e.g. `RoboCup.robots.robot3` (the root element of the scene is called "RoboCup", which has a child compound called "robots", which has a child body called "robot3"). The ball would be called `RoboCup.balls.ball` and robots that aren't controlled by the B-Human software are in the group `RoboCup.extras`.

**Comment by Saman-Khan** [comment]
Thanks

**Comment by chenqiao637** [comment]
邮件已收到，谢谢
