### ISSUE TITLE
Team Behaviour 

### ISSUE THREAD

**Issue by Saman-Khan** [bhuman/BHumanCodeRelease#51]
As the team behaviour is not a part of github code. It is getting really difficult to figure out the particular files to be changed for role assignment during a gameplay. If u can highlight the systematic way of adding team behaviour to current code. The particular files that need a change to implement team behaviour.  Your guidance will be highly appreciated. 
I am not asking for implementation of a team behaviour strategy but the method to add own team behaviour effectively.

**Comment by Saman-Khan** [comment]
As per my understanding of framework, the teamBehaviourstatus that includes teamActivity, teammateRoles, PlayerRoles and timetoReachBall is instantiated as part of teambehaviorcontrol. The behaviour status is modified by respective teamskills e.g TeamActivity,Role,TeammateRoles and TimetoReachBall. TeamBehaviour Control.cpp calls the teamBehaviour Card which calls the No team card that eventually use teamskills to update teambehaviourstatus. 
The updated team behaviours can be used in GameControlCard for selection of Robot skills according to team behaviour status. 
Please let me know if there is anything more to it or if I am missing out on something related to understanding of framework. Your guidance will be appreciated.

**Comment by ahasselbring** [comment]
Please understand that we don't provide support in this regard, especially since this behavior framework doesn't exist in our own code anymore for a year.
