### ISSUE TITLE
WalkatAbsoluteSpeedSkill

### ISSUE THREAD

**Issue by Saman-Khan** [bhuman/BHumanCodeRelease#52]
I am trying to figure-out the basic walking provided in code release. The problem is that when I implement the call in CodereleaseKickatGoalCard.cpp, theWalkAtAbsoluteSpeedSkill(Pose2f(0.0f, 0.0f, walkSpeed)); works for side steps in y direction given the y-argument, for x as -1.0f , it implements the backward walk, it rotates given the rotation angle. However, for positive value of x i.e 1.0f , the robot doesnot walk in x direction as it should. The same is happening for walkAtRelativeSpeed. Please guide to what am i doing wrong . Why the forward walk isn't working.
A prompt reply would be highly appreciated.

**Comment by Saman-Khan** [comment]
Also, if u want to move the robot in which the robot walks to field coordinates (x,y) without any path planner , ignoring the obstacles in its path, what command is to be used?

**Comment by philipniklas-r** [comment]
The `theWalkAtAbsoluteSpeedSkill ` uses absolute values. So if you want the robot to walk forward, you would need to set the speed at a value like 200, corresponding to 200 mm/s. A value of 1 for the x-parameter results in 1 mm/s, that is why the robot seem to not walk forward.

For relative values, like the value 1 meaning 100%, you can use the `theWalkAtRelativeSpeedSkill`.

For walking to a field coordinate, you can use the `theWalkToPointSkill`. This skill needs a relative position to the robot, so you would need to convert the field coordinate into a relative coordinate. Also it has a parameter `disableObstacleAvoidance`, which is probably what you want.

**Comment by Saman-Khan** [comment]
![image](https://user-images.githubusercontent.com/15613013/189542857-db561730-e446-4693-9427-3ecfb46e1595.png)
![image](https://user-images.githubusercontent.com/15613013/189542899-7448745f-d220-420a-9701-f3d22efed136.png)
There was some typo. I am actually trying the same as per your description however, i am only facing this issue to translate robot in x direction. My robot doesnot moves forward. Attaching code snippet and behaviour control log

**Comment by Saman-Khan** [comment]
![image](https://user-images.githubusercontent.com/15613013/189542997-f1e4766f-2eaf-45df-a24d-171e2505a404.png)

**Comment by Saman-Khan** [comment]
![image](https://user-images.githubusercontent.com/15613013/189543037-b84724a3-bbe2-43bf-845e-9d27f1d33121.png)
My robot is not moving in x direction. In my code, as i am testing this, i have given the condition that if the ball is not seen, the robot should walk in x direction , however this isnt happening. There are no comiplation errors whatsoever

**Comment by Saman-Khan** [comment]
Just the forward walk isn't working and I am unable to figure-out why is this happening. If u can help me out, ill be really greatful

**Comment by Saman-Khan** [comment]
As per my understanding , the issue lies in WalkingEngine.cpp as during the code running , i hear a sound stand. When i debugged, i came to know that my weightshiftstatus is equal to emergency stand in beginning , hence the forward translation dont work. If I move around the robot and this gets settled, the robot starts walking. Please help on how to rectify it 
![image](https://user-images.githubusercontent.com/15613013/189545303-6e7ff806-6d10-45a5-9b9f-f5a8ddc38e89.png)

**Comment by roefer** [comment]
My suggestion would be, to execute the MotionRequest manually using the get/set mechanism. If the behavior is the same, clone a second instance of the repository, build it, and check whether the behavior is the same there. If not, you can starting searching for the mistake you made.

**Comment by ahasselbring** [comment]
Is this still related to this issue?

Stopwatches measure runtime, i.e. the time the CPU spends to execute some block of code in one execution cycle (frame). This is not useful to determine the time of physical actions since they extend over many frames.

state_time evaluates as the time (in ms) for which the state is running without interruption. If you want to do an action for a specific time in a CABSL-option, you add a transition like `if(state_time > timeoutInMilliseconds) goto otherState;` (however this is something that is rarely needed in real code). What do you need to save the time for and why wouldn't writing `state_time` to a variable solve that problem? For advanced tasks, it's probably better to save timestamps from `theFrameInfo.time` and calculate with them.

**Comment by Saman-Khan** [comment]
I am sorry. This isn't particularly related to this issue. Actually my robot starts walking from point A to point B. I wanted to know the exact time it took to walk. I thought there would be some way to measure behaviour time in code. Thanks for your time to reply

**Comment by ahasselbring** [comment]
> I wanted to know the exact time it took to walk.
That can be obtained from `state_time` when you are done with that state, but everything else depends very much on how you want to further process this time.

**Comment by Saman-Khan** [comment]
Thanks a lot
