### ISSUE TITLE
root image error

### ISSUE THREAD

**Issue by camz2000** [bhuman/BHumanCodeRelease#53]
Hi! I'm Camila Álvarez from the University of la Sabana, and I'm working with my team in the image processing optimization of the robot NAO, and we find intersting your code. Therefore, with my team, we are trying to compile this repository, but in the part of the root image, appears an error which says the following message:
![image](https://user-images.githubusercontent.com/111761871/195874521-afe495d9-896d-40ea-927a-baf069280b26.png)

It seems that isn't creating a directory that allows the compilation of the code.
I will apreciate if you could guide us to solve this problem.
Thank you so much.

**Comment by balisujohn** [comment]
Definitely make sure you are using Ubuntu 20.04. We have had issues with 22.04 if I remember correctly.

**Comment by ahasselbring** [comment]
> Definitely make sure you are using Ubuntu 20.04. We have had issues with 22.04 if I remember correctly.

That is also my first guess. Creating a root image with 22.04 is definitely not working with the 2021 release, but I think that was yet another error message (something about /etc/hosts).

**Comment by camz2000** [comment]
Hmmm ok. Until Tuesday we have access to the robot, please don't close the chat, and we will try it again. Thank you :)

**Comment by ahasselbring** [comment]
Since I just created a root image (on Linux Mint 20.3 which is based on Ubuntu 20.04), I can more or less rule out that the cause is in the Ubuntu package base. Are you sure this is the first command that fails? (It should be because the script exits whenever a command fails). Otherwise, can you give the output of `ls -l /tmp/b-human-root/etc/systemd/system` after the command failed?

**Comment by camz2000** [comment]
We executed that line `ls -l /tmp/b-human-root/etc/systemd/system` and we have this:

![image](https://user-images.githubusercontent.com/111761871/196482365-784b2db9-bd5d-4dd9-b0b1-e97d5e1c8eb7.png)

It seems that the directory sysinit.target.wants is not created, what should we do?

**Comment by camz2000** [comment]
Another problem that we have is that this libraries aren't installing. We could replace libqt6 to libqy5?

![image](https://user-images.githubusercontent.com/111761871/196489272-c4781487-3c15-4423-b51e-fdc80c76c614.png)

Thank you for your colaboration.

**Comment by ahasselbring** [comment]
You should follow the instructions from https://wiki.b-human.de/coderelease2021/

**Comment by ahasselbring** [comment]
Regarding the original problem: Can you try removing line 104 (`apt-get dist-upgrade`) from `createRootImage` and run the script again?

**Comment by camz2000** [comment]
Thank you so much. It works with the Ubuntu 20.04Lts. Futhermore, the link that you gave us was the correct one. 👍. We aare grateful with you.
