### ISSUE TITLE
mv command not rotating the robot

### ISSUE THREAD

**Issue by Saman-Khan** [bhuman/BHumanCodeRelease#54]
I am trying the mv command to change robot locations in field. The robot moves in x and y coordinates but no rotation is working. 
command mv 100 10 330[100 0 0]
![image](https://user-images.githubusercontent.com/15613013/196052914-c3714de7-e03b-43b2-8ad0-99dca881cce2.png)

**Comment by ahasselbring** [comment]
The brackets in the help indicate that the values are optional and should not be literally placed in the command.

A valid command (that rotates around the x-axis - you may rather want to rotate around the z-axis) is:
```
mv 100 10 330 100 0 0
```

**Comment by Saman-Khan** [comment]
Thanks
