### ISSUE TITLE
SimRobot can't connect robot

### ISSUE THREAD

**Issue by jjxieustb** [bhuman/BHumanCodeRelease#55]
When I used SimRobot open RemoteRobot.ros2 to connect a real Robot, nothing appeared in SimRobot. I can't connect NAO in SimRobot, but used ./login can do it.
![2022-10-19 20-40-05 的屏幕截图](https://user-images.githubusercontent.com/103991224/196694814-482ecce8-9117-43b1-9813-9ad4699d2ead.png)

**Comment by roefer** [comment]
You cannot connect to a NAO that was deployed with Release code.
