### ISSUE TITLE
Can't see my robot in bush using bhuman2019 

### ISSUE THREAD

**Issue by jjxieustb** [bhuman/BHumanCodeRelease#57]
When I use bhuman2019, I can't connect my robot in bush. 
I created robot and installed robot using bhuman2019 code. I can connect it by SSH and copyfiles can work in terminal.

![2022-10-24 21-26-44屏幕截图](https://user-images.githubusercontent.com/103991224/197537073-98606191-5570-44c7-9b00-286ad6c41981.png)

I can see the robot in bhuman2021!
Maybe, I should do something before using bush in bhuman2019?

**Comment by ahasselbring** [comment]
Maybe it has to do with what was fixed in this commit: https://github.com/bhuman/BHumanCodeRelease/commit/599e18d8e57b2d1facbb6e889829e4af7857e822

But generally, old releases are unsupported.
