### ISSUE TITLE
FATAL when using ./createRobot: "[FATAL]: Failed reading the bodyId!"

### ISSUE THREAD

**Issue by Tova-C** [bhuman/BHumanCodeRelease#58]
![2022-10-29 22-40-42](https://user-images.githubusercontent.com/75205639/198837662-fb580427-fb1d-4a6c-b3ee-92baf9cb3aff.png)
Please help me, thank you very much!

**Comment by ahasselbring** [comment]
Is the robot currently running the image `nao-2.8.5.11_ROBOCUP_ONLY_with_root.opn`? The process cannot work otherwise.

**Comment by ahasselbring** [comment]
Judging from the console output, you are not running the latest version (the line "Copying authorized keys" doesn't exist anymore in the most recent release). This may be the problem that was fixed in cf93ccbd35382e05ab1b53afdd58eb7bcabc4255

**Comment by Tova-C** [comment]
Sorry for letting you wait. @ahasselbring I did use the right image. And this is BHuman2019 running on ubuntu20.04. 
But I just left the lab so I may not have the chance to try it today. Can I ask you for help tomorrow?

**Comment by roefer** [comment]
The 2022 code release is the latest version, not 2019.

**Comment by roefer** [comment]
The 2022 code release is the latest version, not 2019.

**Comment by ahasselbring** [comment]
Versions other than 2022 are not supported.
