### ISSUE TITLE
Handling Indirectly accessed Streamable Objects

### ISSUE THREAD

**Issue by Saman-Khan** [bhuman/BHumanCodeRelease#59]
While MODIFY command can be used to view variables. Generally, where the streamable variables are updated, we can write modify command to view values on console. For variables such as BallContactInformation, that have no seperate update call, how can i use MODIFY command to view it. I tried using MODIFY in update function of  BallContactCheckProvider and also inside handlecollisionwithfeet but i am getting syntax error and modify isnt showing contents of contactInfo. Also, why this particular representation is not used in BHFast. I want to know that ball collided with robot. Thanking in anticipation

**Comment by Saman-Khan** [comment]
I am particularly looking as to how it checked that robot foot collided with ball  successfully . I am stuck figuring this out for long time. Any help ass to where to look for will be  appreciated . eagerly waiting for your response

**Comment by Saman-Khan** [comment]
I implemented the lines inside fieldball provider update function. I added a collision check variable and called ballcontactchecker as shown below. However, when i apply force to ball and ball makes contact with robot foot, none of variable gets updated
![image](https://user-images.githubusercontent.com/15613013/199812329-c20d766d-f6a7-4a69-a1f1-86342c3e178d.png)

**Comment by roefer** [comment]
Please note this [file](https://github.com/bhuman/BHumanCodeRelease/blob/coderelease2022/README.md), in particular the second paragraph.
