### ISSUE TITLE
Questions about connecting to Nao with Bhuman

### ISSUE THREAD

**Issue by a7744hsc** [bhuman/BHumanCodeRelease#6]
Dear Bhuman Author,

I encounterred a issue when setting up  Bhuman on Nao, I have struggled for a whole day and cannot find any solution for this, so I tried to write an email to you for help. 

I'm using ubuntu 16.10 and the latest BHumanCodeRelease. The first several steps works fine until the command "./installRobot 192.168.1.103 ",  after this command is run, I can't connect to my robot. Following are the logs and factors when I occur this issue.
1. After the installRobot is done the robot restart it self automaticly, but I didn't find any clue about this restart in the CodeRelease2015.pdf.
2. I'm using a router, both Nao and my PC are connected to it with cable, this router has DHCP enabled(the ip Nao got before restart is 192.168.1.103).

I was trying to figure out the root cause but failed, I wish you can solve some of my confusions.
1. After Nao is refreshed with opennao-atomsystem-image, Should I connect my PC with Nao through a net cable directly? If so, should I configure my PC as a DHCP server?
2. Is reboot after installRobot command excuted a normal case or not? If so, How can I figure out its Ip address after restart?
3. I got a Info "Buggy Ethernet driver detected! Limiting bandwidth to 100 kb/s", what's the root cause of this?

I know connection issue is really a environment related problem, but I wonder if you can give me any advice to figure this out. Please feel free to ask if I didn't make myself clear.
Below is the shell history of my issue. Besides this, I also created a issue on github incase you want to answer my questions on it.

> ./ createRobot -t 1 -r 103 Penny
> ./addRobotIds -ip 192.168.1.103 Penny 
> ./installRobot 192.168.1.103 
> 
> [INFO]: Copying authorized keys. If prompted please enter password twice (usually nao).
> 
> using parameters
>   robotName: Penny
>   address:   192.168.1.103
> 
> [INFO]: Buggy Ethernet driver detected! Limiting bandwidth to 100 kb/s
> [INFO]: Copying files to /tmp/NaoInstall/Penny
> [INFO]: launching install process
> Please enter password for user 'root' (usually also 'root').
> Password: root
> 
> Changed robot name to Penny
> - service wired added to runlevel boot
> - service wireless added to runlevel boot
> - service bhumand added to runlevel default
> - service readonly added to runlevel boot
> - service crash-report-uploader removed from runlevel default
> - service connman removed from runlevel boot
> - service proxydaemon removed from runlevel default
> - service vsftpd removed from runlevel default
> - service nginx removed from runlevel default
> - service naopathe removed from runlevel default
> - service laser removed from runlevel boot
> - service bootprogress_0 removed from runlevel shutdown
> - service bootprogress_25 removed from runlevel boot
> - service bootprogress_50 removed from runlevel boot
> - service bootprogress_75 removed from runlevel boot
> - service bootprogress_100 removed from runlevel default
> - service avahi-daemon removed from runlevel default
> - service lircd removed from runlevel default
> - service bluetooth removed from runlevel boot
> - service sshd removed from runlevel boot
> - service hwclock removed from runlevel boot
> - service sysctl removed from runlevel boot
> - service local removed from runlevel default
> - service urandom removed from runlevel boot
> - service termencoding removed from runlevel boot
> - service root removed from runlevel boot
> - service netmount removed from runlevel default
> - service mtab removed from runlevel boot
> - service sysklogd removed from runlevel boot
> - service hostname removed from runlevel boot
> - service modules removed from runlevel boot
> - service savecache removed from runlevel shutdown
> - service firewall_mode removed from runlevel default
> - service ofono removed from runlevel default
> - service pulseaudio removed from runlevel default
> - service qimessaging-json removed from runlevel default
> - service udev-postmount removed from runlevel default
> - service sshd added to runlevel default
>   [INFO] rebooting

Thanks very much.

**Comment by bhuman** [comment]
1. You should be able to reach your NAO if you directly plugin the ethernet cable to its head and use the IP address 192.168.1.103. Use the script "login" in Make/Linux, Make/macOS, or Make/VS2015 to login to the robot. It will automatically use the ssh key we provide in Config/Keys.

2. installRobot reboots the robot. Otherwise, some of the changes would not have an effect.

3. The ethernet driver that Aldebaran provides is buggy. It crashes the whole system when larger amounts of data are transferred quickly. Therefore, we lower the upload speed in installRobot. We then install a new driver. Therefore, if you run installRobot again on a robot that is already installed, the transfer will not be slowed down anymore.

**Comment by a7744hsc** [comment]
Thanks very much for your quick response. I can connect to my nao with your advice. By the way, could you introduce some learning material except the `coderelease2015.pdf`?

**Comment by ash22194** [comment]
Hey, I'm facing a similar issue. I flashed my robot and ran the installRobot script, the robot rebooted and then gets stuck during reboot (chest light remains white and no startup sound). I tried ssh but it didn't work. I tried the login script "login 192.168.1.103" but it didn't work. I tried to flash it again, to get it back to the factory settings but even while flashing (now) it gets stuck at the white light. 
Can you help? Thanks in advance!

**Comment by bhuman** [comment]
Sometimes, Aldebaran's flashing procedure gets stuck. Simply try it again. It might also help not to connect an Ethernet cable while flashing. There also is a micro USB port inside the head that can be used to log into the robot. On Linux, you can use

sudo screen /dev/ttyUSB0 115200

to connect to the robot with the right cable and watch it booting.

**Comment by a7744hsc** [comment]
@ash22194 is your problem solved?  I believe I should close this issue because mine is solved.
Please create another one if you need further help.
