### ISSUE TITLE
Missing Figure in SimRobot Wiki page

### ISSUE THREAD

**Issue by antbono** [bhuman/BHumanCodeRelease#61]
Hello guys!

I think there is something wrong in the SimRobot wiki page since I see a text file instead of a picture explaining connections among different libraries. 

![err](https://user-images.githubusercontent.com/7023471/200303208-ce8e4984-6270-4517-a51b-da64f3eeacf8.png)

**Comment by roefer** [comment]
It seems as if the Mermaid plugin is not working anymore.

**Comment by roefer** [comment]
We resolved the issue.
