### ISSUE TITLE
FATAL when using ./createRobot：[FATAL]:Can't change access rights  on  Nao's  '.ssh'  folder

### ISSUE THREAD

**Issue by DuanCB** [bhuman/BHumanCodeRelease#64]

**Comment by DuanCB** [comment]
/home/dcb/图片/111.jpg

**Comment by DuanCB** [comment]
![111](https://user-images.githubusercontent.com/72556098/203742409-256c6ad3-c27f-4384-95c4-9db299f3d71d.jpg)

**Comment by ahasselbring** [comment]
2019 is not the most recent version. We don't support that anymore.
