### ISSUE TITLE
When I open the bush,I can't see the power and I can't deploy the code into the Robot,But I can ping the robot.

### ISSUE THREAD

**Issue by DuanCB** [bhuman/BHumanCodeRelease#65]
![234](https://user-images.githubusercontent.com/72556098/203837603-57f66331-1ece-41b9-9c68-885149bf0a31.jpg)

**Comment by ahasselbring** [comment]
This is still not the 2022 version.

**Comment by roefer** [comment]
No idea. This is handled by Qt.
