### ISSUE TITLE
Questions about Autonomous Calibration in Bhuman2022

### ISSUE THREAD

**Issue by Tova-C** [bhuman/BHumanCodeRelease#66]
During the process of autonomous calibration in
 BHuman2022, After the robot rotated four rounds it didn't seem to want to stop. Is this a normal situation?
![IMG_20221126_003412](https://user-images.githubusercontent.com/75205639/204026924-bc833eba-0dc2-43e2-8141-b4def497df75.jpg)
![IMG_20221126_003356](https://user-images.githubusercontent.com/75205639/204026934-c70221dd-f5aa-4766-b9c6-34e1b796aff4.jpg)
![IMG_20221126_003351](https://user-images.githubusercontent.com/75205639/204026940-1110b6d9-47c3-4a9b-971e-974f5d43e6cd.jpg)

**Comment by philipniklas-r** [comment]
>  After the robot rotated four rounds

So the robot stood once on each leg, rotated by 180 degrees, and repeated it three more times (so overall four times), or did it stood on one leg, started walking without rotating multiple times?

The "Adjusted Stable Feet Position" message hints to the second one. This messages means, that the robot thought to be unstable, therefore to prevent falling, it started to walk and try again, but with some offsets (the x and y values). But every try was "unstable", so it tried over and over again. 

This can happen from different reasons:
- the robot was moved while booting up. The gyro values then have offsets and the robot thinks it is not standing still. Turn it fully off and on again to resolve those gyro value offsets. We have a detection for that, but it is not perfect.
- the floor could be uneven. On the image it seems even, so I would rule that out
- the robot is loose. While doing this "posture" most of the time (at least all of our robots) will have one fast "swing" to the side, which could cause the software to think the robot is unstable and needs to start walking. As long as a human is around to catch the robot, you could increase the thresholds. The parameters can be found in the module doing the calibration process: `Src\Modules\MotionControl\CalibrationEngine\CalibrationEngine.h`. The parameters are defined in the ``DEFINES_PARAMETERS`` block. I think you need increase ``yMaxCOMDeviation`` and ``yMaxCOMDeviationStanding``, as those are the deviation thresholds for the y-axis, which seems to be the problem. 
As long as you would catch the robot by hand if something fails, you can increase those thresholds as much as you want. But I think increasing them by 10 (so -30.f and 30.f) could already be enough.

**Comment by Tova-C** [comment]
The problem has been overcome. Thanks so much for the help!
The initial situation is that the robot stood on one leg.
During the check, I first turn off the robot when it said something about the gyro value. So the probable cause 1 was ruled out. And the cause 2 was cleared later. At last We adjusted
 the parameters in the file CalibrationEngine.h and then the problem was completely settled.
