### ISSUE TITLE
Problem with B-Human2022 configuring the environment

### ISSUE THREAD

**Issue by Jianpanfeixingdashi** [bhuman/BHumanCodeRelease#68]
Excuse me. I'm wondering about we sometimes fail the clone. There is always a problem when we successfully cloned it, ./generate always failed.

**Comment by roefer** [comment]
Which `generate`, i.e. on which operating system? What is the output of `generate`?

**Comment by Jianpanfeixingdashi** [comment]
On Linux system and it is the step that to generate CMake caches

![截图 2023-01-10 18-07-11](https://user-images.githubusercontent.com/122345344/211522549-f35e6b7a-35f7-4208-9773-417c1525beb5.png)
The output of the generate is above

**Comment by roefer** [comment]
Do other CMake-based projects work on your system when placed in a neighboring directory? This appears to be a problem of CMake and has nothing to do with our code.

**Comment by Jianpanfeixingdashi** [comment]
OK, I will try thank you
