### ISSUE TITLE
Mac ARM Compilation

### ISSUE THREAD

**Issue by AdamLabiosa** [bhuman/BHumanCodeRelease#69]
Hello,

Currently I am trying to compile and open the 2022 codebase on an M2 MacBook. 

I am able to run the "Make/macOS/generate -r" command with no stated errors when doing so and the B-Human.xcodeproj is generated into the correct folder but when I go to open the project up, Xcode launches but the project does not come up, and instead just spins and never ends up opening up the project.

I have used the 2022 code before on an intel Mac and was able to successfully compile and run the project like is stated so it seems to work just fine on intel Macs.

I'm using MacOS 13.1, Xcode 14.2 and CMake 3.25.1. I saw the message about not directly supporting these versions but as far as I know there is no way to downgrade MacOS or Xcode so I am stuck there. It may be an issue with CMake but it seems to compile without errors so I am unsure there.

I have tried both "Make/macOS/generate -r" and "Make/macOS/generate" and get the same issue. I am wondering if there is some incompatablilty of the codebase and M2 Macs that can be fixed or if I have it setup incorrectly.

Thank you!

**Comment by roefer** [comment]
Hi,

I added a commit from our internal repository that you can try. Either CMake or Xcode changed the directory structure in the build folder at some point. However, I cannot remember that Xcode actually refused to start back then.

**Comment by AdamLabiosa** [comment]
It doesn't seem like that changed it unfortunately. I tried both -r and without it and still have the same issue. Would it be worth trying a different version of CMake? That is the only thing I could think of or if you have other ideas that would also be wonderful.

**Comment by roefer** [comment]
I just tested my local clone of the code release with CMake 3.25.1. Xcode starts without a problem both with `generate` and `generate -r`. Maybe you should try to delete the folder `Build` and `Make/macOS/B-Human.xcodeproj` as well as the symbolic link `Util/Buildchain/macOS/bin/cmake` and run `generate` again.
CMake creates an Xcode project using absolute paths to a all the files. Are there any special characters in the path?

**Comment by AdamLabiosa** [comment]
Thank you! It works now. I think it may have been something with the installation of CMake was incorrect for some reason I reinstalled it and then deleted the folders and files and reran generate and it worked.

Thank you for the help!
