### ISSUE TITLE
Running a behavior

### ISSUE THREAD

**Issue by ash22194** [bhuman/BHumanCodeRelease#7]
I'm new to this code base and am trying to run the default behavior provided with the code on the Nao, but am unable to do so. I am able to connect the robot to the RoboCup Game Controller. However when the state is set to playing the robot doesn't execute the behavior defined in the option Soccer.h.
How do I trigger this behavior? When you write a new behavior, how do I set it up such that it starts executing that behavior when the bhuman process on the robot starts up?

**Comment by bhuman** [comment]
Actually, the behavior should run automatically, after the chest button was pressed once to let the robot get up.
