### ISSUE TITLE
Missing package for creating the root image

### ISSUE THREAD

**Issue by StellaASchlotter** [bhuman/BHumanCodeRelease#70]
I followed the instructions from https://wiki.b-human.de/coderelease2022/getting-started/#deploying-the-software
I used a fresh Ubuntu 22.04 installation in WSL.

Running `sudo Install/createRootImage <path to original Aldebaran OPN>`  gave me the error on line 155
```
tar (child): lbzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

It was solved by installing bzip2
```
sudo apt install bzip2
```
Maybe the docs could get updated with the extra package.

**Comment by ahasselbring** [comment]
Hi Stella, thanks for reporting! I have added it to the list at https://wiki.b-human.de/coderelease2022/getting-started/#creating-a-root-image

(The dependency lists have been created with a desktop install of Ubuntu, and probably bzip2 is installed implicitly there.)
