### ISSUE TITLE
Live Stream Robot Perception

### ISSUE THREAD

**Issue by byyhong** [bhuman/BHumanCodeRelease#73]
Is there a way to live stream what the robot is seeing?
I tried connecting to the robot remotely using the sc <wlan address> command(this part worked) on the remoteRobot.ros2 scene and enter "vi image Upper upperImage" to add an image view to the robot after selecting the robot by entering robot <name>, but nothing shows up in the scene graph. The image folder with upperImage was not added to the scene graph as it did with other scene graphs such as Game.ros2. I was wondering if we can live stream the robot perception, or is it intentionally hidden for some reason? Thanks!

**Comment by roefer** [comment]
You can only connect to the robot if the project "Nao" was compiled with the configuration "Develop" and `bhuman` is running on the robot ("Debug" would also work, but is generally too slow to be usable on the robot). You can follow the connection process in SimRobot's status bar. If is contains something like "polling for ...", it is still establishing the connection. The scene "RemoteRobot.ros2" already adds views for both cameras to the scene tree, but this is only done after the connection was established.

**Comment by byyhong** [comment]
I already compile Nao, and I think I was able to establish connection because after entering the command sc <name> <wlan address> it said <robot name> connected to <address, 0.0kb/s>. The robot appeared in the scene graph the the modules folder, but I didn’t see the image view for the robot, so I tried the vi image Upper upperImage command, and it said polling for idModuleTable at the bottom.

**Comment by byyhong** [comment]
It said polling for idModuleTable, and it didn’t move on from that. Is the connection suppose to take a long time?
