### ISSUE TITLE
polling for idModuelTable

### ISSUE THREAD

**Issue by byyhong** [bhuman/BHumanCodeRelease#74]
It said polling for idModuleTable when I was trying to connect to the robots through remoteRobot.ros2, and it didn’t move on from that. Is the connection suppose to take a long time?

_Originally posted by @byyhong in https://github.com/bhuman/BHumanCodeRelease/issues/73#issuecomment-1489108648_

**Comment by roefer** [comment]
No. Did you deploy the "Develop" version to the robot (and is `bhuman` running at all)?

**Comment by byyhong** [comment]
I compiled deployed the developed version on bush that’s what you mean by deploy robot. The robot is on. I am not sure if you mean that the bhuman code is running, but the code is running.

**Comment by roefer** [comment]
In that case, the connection should not take more than one or two seconds to establish.

**Comment by byyhong** [comment]
I figured it out. Turns out I've selected the Release version the whole time. Now it works. Thank you so much for your help!
