### ISSUE TITLE
In windows11，run generate.cmd  error

### ISSUE THREAD

**Issue by Djiutian** [bhuman/BHumanCodeRelease#75]
In Windows 11，Run Make/Windows/generate.cmd 
Run  error
![image](https://user-images.githubusercontent.com/130020460/230259899-6b109a2c-3f9c-4aba-906c-06f8e1a6cca6.png)

**Comment by roefer** [comment]
Did you clone the repository ("This manual assumes that you cloned the B-Human repository including the submodules.")?

**Comment by Djiutian** [comment]
yes,I recloned it,but I ran it again and got an error
![`EMY5)VL)X5X72JT4PRTMHD](https://user-images.githubusercontent.com/130020460/230575101-203d08ad-63b7-48e0-a7ec-da8d6a9a218e.png)

**Comment by roefer** [comment]
Did you do everything [this section](https://wiki.b-human.de/coderelease2022/getting-started/#setting-up-the-development-computer) told you to?

**Comment by Djiutian** [comment]
Yes, I followed that

**Comment by roefer** [comment]
According to the error message, `ninja` is missing. However,

    wsl apt -y install astyle ccache clang cmake llvm mold net-tools ninja-build pigz rsync xxd

should have installed it.

**Comment by Djiutian** [comment]
I've already done that, But it still run error
![8VSXE9{(L}NB3SX{L@6ZD6Q](https://user-images.githubusercontent.com/130020460/230586225-88fe0e6b-8b7a-461d-969d-91953225516b.png)

**Comment by roefer** [comment]
Do you always use the account `Administrator`, also for the call to `generate.cmd`?

**Comment by Djiutian** [comment]
yes, running as administrator is still an error

**Comment by roefer** [comment]
If you call `bash` from the Windows command prompt, are you then inside the WSL?

**Comment by Djiutian** [comment]
Can you tell me how to do it correctly, when I run the same operation on another computer without any errors

**Comment by roefer** [comment]
Sorry, but you have to figure that out on your own.
