### ISSUE TITLE
NAO Compilation Mac

### ISSUE THREAD

**Issue by AdamLabiosa** [bhuman/BHumanCodeRelease#76]
Hey BHuman team,

I'm currently working on getting code to compile and deploy to the NAOs and I'm having some trouble. I'm working on an ARM Mac.

This problem is happening on a fresh clone of the main branch and I was just wondering if you have run into it before. Following the steps on the wiki, I'm able to compile the Xcode project just fine with the command Make/MacOS/generate. I am then able to successfully launch both SimRobot and Bush without any errors.

In bush I go to compile the NAO code using the compile button at the top as seen here:

<img width="148" alt="Screenshot 2023-04-19 at 1 36 02 PM" src="https://user-images.githubusercontent.com/57111568/233168719-8590c364-900d-4a70-8e5d-bb9fd2018200.png">

Then I end up seeing this error:
<img width="853" alt="Screenshot 2023-04-19 at 1 36 53 PM" src="https://user-images.githubusercontent.com/57111568/233168904-23f4ae22-3dde-4f3b-b63a-b7fa79d903c4.png">

I've spent lots of time attempting things like adding a custom build setting to the project like this CODE_SIGNING_ALLOWED=NO, as many solutions say to do but this simply gets overwritten and goes back to default every time I try to compile.

If you are not sure that is totally fine I was just wondering if you had any advice for me!

Thanks so much!
Adam

Edit:

This also happens with compiling with -r and then running the command Make/MacOS/deploy Develop. So I don't think it is a rosetta problem or something of that nature.

**Comment by roefer** [comment]
Hi,
in November, we added these commands to the Nao.cmake, Tests.cmake, and bush.cmake (with matching TARGET):

    set_property(TARGET Nao PROPERTY XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "-")

This may have to do with the problem. Each version of Xcode introduces new surprises.

**Comment by AdamLabiosa** [comment]
Thanks! That was exactly it. I just commented out that line and it compiled exactly as expected thanks again!
