### ISSUE TITLE
Keychain when building simulator through bush

### ISSUE THREAD

**Issue by byyhong** [bhuman/BHumanCodeRelease#78]
Hi, when I was building the simulator through bush on Xcode, it said I need to enter a keychain. What's the keychain for running this program? Is it stored in  a file? Thank you!
![image](https://user-images.githubusercontent.com/60803591/235515902-8631d381-3924-44a7-9800-f0a41c82d61d.png)

**Comment by roefer** [comment]
The password is "nao". The keychain is installed by `generate`. Normally, the keychain is automatically unlocked in a pre-build step, but this did not seem to work in your case.
