### ISSUE TITLE
excuse me, I am confused about the meaning of these curves

### ISSUE THREAD

**Issue by Jianpanfeixingdashi** [bhuman/BHumanCodeRelease#79]
This is from the Bhuman 2019, in Simrobot, kickview
![微信图片_20230510091919](https://github.com/bhuman/BHumanCodeRelease/assets/122345344/1fb3a17f-ad80-4f80-9d14-853f717d68fd)

**Comment by roefer** [comment]
To cite the readme file:

> You can build on this software, but you have to make do with the documentation we released.

Neither the kick view nor the script that creates the two plots exist anymore in our latest release.
