### ISSUE TITLE
questions about making  my own mofs

### ISSUE THREAD

**Issue by SkyCloudShang** [bhuman/BHumanCodeRelease#8]
Dear friend：
     I am a learner of your code. In your code,I found some mof files with special actions.However,I don't know how to make my own mof files. Can you tell me how your team make such mof files? Using what software?or something else.

Thanks a lot!

**Comment by bhuman** [comment]
All there is to know is described in the section "8.4 Special Actions" of the file CodeRelease2016.pdf that you probably already read. There also is the command "mof" (page 154) in the Simulator to recompile the current mof files and to send the result to the robot for testing. The testing itself is usually done by just setting the "representation:MotionRequest" from the Simulator console window or through a Data View.
