### ISSUE TITLE
How does BHuman2022 alleviate robot stiffness

### ISSUE THREAD

**Issue by Djiutian** [bhuman/BHumanCodeRelease#80]
Hi,
How does BHuman2022 relieve the stiffness of the robot, which in the pre-2022 version was to press the chest button three times in a row, but it doesn't seem to work in the 2022 version

**Comment by roefer** [comment]
As the 2022 SPL rulebook says in section 3.2: 

> From any state it can be transitioned to the unstiff state, shown as a blue arrow, via pressing all three head buttons.
