### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by shentry** [bhuman/BHumanCodeRelease#81]
Hello, I would like to ask why I have such a problem during deployment and how can I solve it？
![image](https://github.com/bhuman/BHumanCodeRelease/assets/111497882/5a76c229-e86a-4531-83ac-f9299027d572)

**Comment by ahasselbring** [comment]
The password prompt and the following error message indicate that the robot is not actually running the B-Human operating system. Can you confirm that you have
- created a .opn image (by first [creating a root image](https://wiki.b-human.de/coderelease2022/getting-started/#creating-a-root-image) and then running [`deploy -i`](https://wiki.b-human.de/coderelease2022/getting-started/#deploying-the-software))
- transferred that image to a USB drive as described [here](http://doc.aldebaran.com/2-8/software/naoflasher/naoflasher.html)
- installed the image on the robot by pressing the chest button long enough for the chest button to flash blue (as described [here](http://doc.aldebaran.com/2-8/software/naoflasher/naoflasher.html#ii-plugging-the-usb-stick)) and then waited until it shut down?

**Comment by shentry** [comment]
I would like to ask you how to connect the robot to bush after I install yhe code of BHuman on the robot and press the button on nao's chest without reporting the IP?

**Comment by roefer** [comment]
This is all described in https://wiki.b-human.de/coderelease2022/getting-started/ .
