### ISSUE TITLE
macos build error

### ISSUE THREAD

**Issue by qiaoyu113** [bhuman/BHumanCodeRelease#82]
Dear developers,

When I was compiling SimRobot-Develop in the bhuman project using macos, I kept failing because of SimulatedNao： 

1. Library not found for -ld_classic
2. Linker command failed with exit code 1 (use -v to see invocation)

xcode version: 14.3 (14E222b)

I am stuck here and cannot go on. I hope you can help me. It is very important to me, thank you very much

**Comment by qiaoyu113** [comment]
<img width="1136" alt="WechatIMG575" src="https://github.com/bhuman/BHumanCodeRelease/assets/22719481/50f80e4e-e381-4cfd-9332-0e7611c83bf2">

**Comment by kantipudikesava** [comment]
Any update on this issue. Facing the same error in iOS
