### ISSUE TITLE
[FATAL] "Invalid Aldebaran image." when using proper opn, createRootimage

### ISSUE THREAD

**Issue by hydroakri** [bhuman/BHumanCodeRelease#83]
Checking the opn file by: `dd if="${naoOPN}" skip=96 bs=1 count=8 status=none | xxd -p`

It output `7a59c4422a2221b0` rather than "0000000000100000"

I am sure the opn "nao-2.8.5.11_ROBOCUP_ONLY_with_root.opn" is correct and it's running on nao v6

**Comment by ahasselbring** [comment]
This is very strange. That command checks the bytes 95-103 of the image, which contain the length of a script that is embedded in the image. All OPN files from Aldebaran have 0x0000000000100000 there. Can you share the system on which you are running this and the exact command?

By the way, the RoboCup image should have a size of 681519104 bytes, and a SHA256 checksum of fa1667f60b21c2c79cb7dc50f70d3ce67cf19b04354c48677d2a03689c0fa727.

**Comment by hydroakri** [comment]
I download the opn from
`https://www2.informatik.hu-berlin.de/~naoth/ressources/Softbank/nao-2.8.5.11_ROBOCUP_ONLY_with_root.opn`
I will checksum later.

**Comment by ahasselbring** [comment]
Something must have went wrong with the download then. I have just checked the file from your URL which is binary identical (i.e. has the same hash) as mine, so your file must be different.
