### ISSUE TITLE
Implementation of Rust GameController in 2023 Code Release

### ISSUE THREAD

**Issue by juangomezru** [bhuman/BHumanCodeRelease#86]
Hello, I hope you're all doing well.

We're currently running CodeRelease 2023 on some NaoV6 robots. We've successfully connected them to WiFi, and DeployDialog is functioning perfectly. However, we're encountering issues trying to integrate [GameController](https://github.com/RoboCup-SPL/GameController3) with the CodeRelease. Both our robots and the computer running the game controller are on the same network. In the GameController, we've configured a team with the same Magic Number as our robots' IPs and Port. Despite this setup, the robots aren't responding to GameController orders, nor is the GameController detecting messages from the robots. 
Any help with what could be going wrong or how to make our implementation work would be highly appreciated.

**Comment by ahasselbring** [comment]
Some suggestions:
1. Which version of the GameController are you using (e.g. a binary release, or compiled yourself)? If you compiled the GameController yourself within the last two weeks, it won't be compatible with the B-Human code release 2023 anymore (new RoboCupGameControlData version).
2. Do you have a firewall that blocks the GameController? (it needs to be allowed to send/receive UDP packets on a number of ports, see its README)
3. Can you verify that you select the correct network interface in the GameController launcher? You have to set its IP configuration (by default something in the 10.0.0.0/16 range) before starting the GameController.
4. As you are mentioning the magic number: This one does not have anything to do with the GameController. What is important is the "team number".

**Comment by juangomezru** [comment]
We managed to resolve the issue! Thank you very much. For anyone encountering this problem in the future, the crucial step was setting the interface IP of the computer running the GameController to an IP within the 10.0.0.0/16 range, as suggested by @ahasselbring, and using the 1.0.0 release of GameController.

Thank you once again, @ahasselbring! 😊
