### ISSUE TITLE
Where is the codes of handling the Ready state when gc starts the game?

### ISSUE THREAD

**Issue by infCraft** [bhuman/BHumanCodeRelease#87]
In the rules of the Robocup 2024, robots turn to the Ready state when the main referee holds up his/her hand wearing read gloves, or they will delay 30s before turning to the Ready state, which means that they only have 15s to walk into their initial position (which is not enough). So we are wondering how can we grab the motion played by referees. Does bhuman 2024 has the codes controlling it? If it does, where is it?
Thanks for your reply!

**Comment by roefer** [comment]
This is a rule change for RoboCup 2024, so it is not part of our 2023 code release. It will be part of our 2024 code release, which will probably appear in October.
