### ISSUE TITLE
SimRobot Documentation

### ISSUE THREAD

**Issue by gortium** [bhuman/BHumanCodeRelease#9]
I would like to modify SimRobot to integrate a new module. How would i do this? I am searching for documentation and found that there was a SimRobotHelp in earlier version but the API section was not completed.

I would like to do play / pause on the sim by script. Is it already possible? 

Is there other documentation elsewhere? If not, can you give me some hints as to where to look and what to do please?

Thank you!

**Comment by bhuman** [comment]
No, there is no other documentation. The simulator also does not have a scripting interface.
